/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePrinterRequestCapabilitiesInner
 */
export interface CreatePrinterRequestCapabilitiesInner {
}

/**
 * Check if a given object implements the CreatePrinterRequestCapabilitiesInner interface.
 */
export function instanceOfCreatePrinterRequestCapabilitiesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreatePrinterRequestCapabilitiesInnerFromJSON(json: any): CreatePrinterRequestCapabilitiesInner {
    return CreatePrinterRequestCapabilitiesInnerFromJSONTyped(json, false);
}

export function CreatePrinterRequestCapabilitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrinterRequestCapabilitiesInner {
    return json;
}

export function CreatePrinterRequestCapabilitiesInnerToJSON(value?: CreatePrinterRequestCapabilitiesInner | null): any {
    return value;
}

