/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePrinterRequest
 */
export interface CreatePrinterRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePrinterRequest
     */
    brand_name: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePrinterRequest
     */
    model_name: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreatePrinterRequest
     */
    capabilities: Array<CreatePrinterRequestCapabilitiesEnum>;
    /**
     * 
     * @type {string}
     * @memberof CreatePrinterRequest
     */
    location: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePrinterRequest
     */
    printer_address: string;
}


/**
 * @export
 */
export const CreatePrinterRequestCapabilitiesEnum = {
    Print: 'print',
    Scan: 'scan',
    Copy: 'copy',
    Fax: 'fax',
    Color: 'color',
    DoubleSided: 'double_sided'
} as const;
export type CreatePrinterRequestCapabilitiesEnum = typeof CreatePrinterRequestCapabilitiesEnum[keyof typeof CreatePrinterRequestCapabilitiesEnum];


/**
 * Check if a given object implements the CreatePrinterRequest interface.
 */
export function instanceOfCreatePrinterRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "brand_name" in value;
    isInstance = isInstance && "model_name" in value;
    isInstance = isInstance && "capabilities" in value;
    isInstance = isInstance && "location" in value;
    isInstance = isInstance && "printer_address" in value;

    return isInstance;
}

export function CreatePrinterRequestFromJSON(json: any): CreatePrinterRequest {
    return CreatePrinterRequestFromJSONTyped(json, false);
}

export function CreatePrinterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrinterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'brand_name': json['brand_name'],
        'model_name': json['model_name'],
        'capabilities': json['capabilities'],
        'location': json['location'],
        'printer_address': json['printer_address'],
    };
}

export function CreatePrinterRequestToJSON(value?: CreatePrinterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'brand_name': value.brand_name,
        'model_name': value.model_name,
        'capabilities': value.capabilities,
        'location': value.location,
        'printer_address': value.printer_address,
    };
}

