/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserFile } from './UserFile';
import {
    UserFileFromJSON,
    UserFileFromJSONTyped,
    UserFileToJSON,
} from './UserFile';

/**
 * 
 * @export
 * @interface CreateUserFile200Response
 */
export interface CreateUserFile200Response {
    /**
     * 
     * @type {UserFile}
     * @memberof CreateUserFile200Response
     */
    file: UserFile;
}

/**
 * Check if a given object implements the CreateUserFile200Response interface.
 */
export function instanceOfCreateUserFile200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function CreateUserFile200ResponseFromJSON(json: any): CreateUserFile200Response {
    return CreateUserFile200ResponseFromJSONTyped(json, false);
}

export function CreateUserFile200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserFile200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': UserFileFromJSON(json['file']),
    };
}

export function CreateUserFile200ResponseToJSON(value?: CreateUserFile200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': UserFileToJSON(value.file),
    };
}

