/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Printer } from './Printer';
import {
    PrinterFromJSON,
    PrinterFromJSONTyped,
    PrinterToJSON,
} from './Printer';

/**
 * 
 * @export
 * @interface CreatePrinter200Response
 */
export interface CreatePrinter200Response {
    /**
     * 
     * @type {Printer}
     * @memberof CreatePrinter200Response
     */
    printer: Printer;
}

/**
 * Check if a given object implements the CreatePrinter200Response interface.
 */
export function instanceOfCreatePrinter200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "printer" in value;

    return isInstance;
}

export function CreatePrinter200ResponseFromJSON(json: any): CreatePrinter200Response {
    return CreatePrinter200ResponseFromJSONTyped(json, false);
}

export function CreatePrinter200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrinter200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'printer': PrinterFromJSON(json['printer']),
    };
}

export function CreatePrinter200ResponseToJSON(value?: CreatePrinter200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'printer': PrinterToJSON(value.printer),
    };
}

