/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PrinterJob } from './PrinterJob';
import {
    PrinterJobFromJSON,
    PrinterJobFromJSONTyped,
    PrinterJobToJSON,
} from './PrinterJob';

/**
 * 
 * @export
 * @interface CreatePrinterJob200Response
 */
export interface CreatePrinterJob200Response {
    /**
     * 
     * @type {PrinterJob}
     * @memberof CreatePrinterJob200Response
     */
    printer_job: PrinterJob;
}

/**
 * Check if a given object implements the CreatePrinterJob200Response interface.
 */
export function instanceOfCreatePrinterJob200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "printer_job" in value;

    return isInstance;
}

export function CreatePrinterJob200ResponseFromJSON(json: any): CreatePrinterJob200Response {
    return CreatePrinterJob200ResponseFromJSONTyped(json, false);
}

export function CreatePrinterJob200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrinterJob200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'printer_job': PrinterJobFromJSON(json['printer_job']),
    };
}

export function CreatePrinterJob200ResponseToJSON(value?: CreatePrinterJob200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'printer_job': PrinterJobToJSON(value.printer_job),
    };
}

