/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SystemConfiguration } from './SystemConfiguration';
import {
    SystemConfigurationFromJSON,
    SystemConfigurationFromJSONTyped,
    SystemConfigurationToJSON,
} from './SystemConfiguration';

/**
 * 
 * @export
 * @interface GetSystemConfiguration200Response
 */
export interface GetSystemConfiguration200Response {
    /**
     * 
     * @type {SystemConfiguration}
     * @memberof GetSystemConfiguration200Response
     */
    system_configuration: SystemConfiguration;
}

/**
 * Check if a given object implements the GetSystemConfiguration200Response interface.
 */
export function instanceOfGetSystemConfiguration200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "system_configuration" in value;

    return isInstance;
}

export function GetSystemConfiguration200ResponseFromJSON(json: any): GetSystemConfiguration200Response {
    return GetSystemConfiguration200ResponseFromJSONTyped(json, false);
}

export function GetSystemConfiguration200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSystemConfiguration200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'system_configuration': SystemConfigurationFromJSON(json['system_configuration']),
    };
}

export function GetSystemConfiguration200ResponseToJSON(value?: GetSystemConfiguration200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'system_configuration': SystemConfigurationToJSON(value.system_configuration),
    };
}

