/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserFile } from './UserFile';
import {
    UserFileFromJSON,
    UserFileFromJSONTyped,
    UserFileToJSON,
} from './UserFile';

/**
 * 
 * @export
 * @interface ListUserFiles200Response
 */
export interface ListUserFiles200Response {
    /**
     * 
     * @type {Array<UserFile>}
     * @memberof ListUserFiles200Response
     */
    files: Array<UserFile>;
}

/**
 * Check if a given object implements the ListUserFiles200Response interface.
 */
export function instanceOfListUserFiles200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "files" in value;

    return isInstance;
}

export function ListUserFiles200ResponseFromJSON(json: any): ListUserFiles200Response {
    return ListUserFiles200ResponseFromJSONTyped(json, false);
}

export function ListUserFiles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUserFiles200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'files': ((json['files'] as Array<any>).map(UserFileFromJSON)),
    };
}

export function ListUserFiles200ResponseToJSON(value?: ListUserFiles200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'files': ((value.files as Array<any>).map(UserFileToJSON)),
    };
}

