/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PrinterJob } from './PrinterJob';
import {
    PrinterJobFromJSON,
    PrinterJobFromJSONTyped,
    PrinterJobToJSON,
} from './PrinterJob';

/**
 * 
 * @export
 * @interface ListPrinterJobs200Response
 */
export interface ListPrinterJobs200Response {
    /**
     * 
     * @type {Array<PrinterJob>}
     * @memberof ListPrinterJobs200Response
     */
    printer_jobs: Array<PrinterJob>;
}

/**
 * Check if a given object implements the ListPrinterJobs200Response interface.
 */
export function instanceOfListPrinterJobs200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "printer_jobs" in value;

    return isInstance;
}

export function ListPrinterJobs200ResponseFromJSON(json: any): ListPrinterJobs200Response {
    return ListPrinterJobs200ResponseFromJSONTyped(json, false);
}

export function ListPrinterJobs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPrinterJobs200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'printer_jobs': ((json['printer_jobs'] as Array<any>).map(PrinterJobFromJSON)),
    };
}

export function ListPrinterJobs200ResponseToJSON(value?: ListPrinterJobs200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'printer_jobs': ((value.printer_jobs as Array<any>).map(PrinterJobToJSON)),
    };
}

