/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Printer
 */
export interface Printer {
    /**
     * 
     * @type {number}
     * @memberof Printer
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Printer
     */
    brand_name: string | null;
    /**
     * 
     * @type {string}
     * @memberof Printer
     */
    model_name: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Printer
     */
    capabilities: Array<PrinterCapabilitiesEnum>;
    /**
     * 
     * @type {string}
     * @memberof Printer
     */
    location: string | null;
    /**
     * 
     * @type {string}
     * @memberof Printer
     */
    printer_address: string;
    /**
     * 
     * @type {boolean}
     * @memberof Printer
     */
    is_enabled: boolean;
}


/**
 * @export
 */
export const PrinterCapabilitiesEnum = {
    Print: 'print',
    Scan: 'scan',
    Copy: 'copy',
    Fax: 'fax',
    Color: 'color',
    DoubleSided: 'double_sided'
} as const;
export type PrinterCapabilitiesEnum = typeof PrinterCapabilitiesEnum[keyof typeof PrinterCapabilitiesEnum];


/**
 * Check if a given object implements the Printer interface.
 */
export function instanceOfPrinter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "brand_name" in value;
    isInstance = isInstance && "model_name" in value;
    isInstance = isInstance && "capabilities" in value;
    isInstance = isInstance && "location" in value;
    isInstance = isInstance && "printer_address" in value;
    isInstance = isInstance && "is_enabled" in value;

    return isInstance;
}

export function PrinterFromJSON(json: any): Printer {
    return PrinterFromJSONTyped(json, false);
}

export function PrinterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Printer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'brand_name': json['brand_name'],
        'model_name': json['model_name'],
        'capabilities': json['capabilities'],
        'location': json['location'],
        'printer_address': json['printer_address'],
        'is_enabled': json['is_enabled'],
    };
}

export function PrinterToJSON(value?: Printer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'brand_name': value.brand_name,
        'model_name': value.model_name,
        'capabilities': value.capabilities,
        'location': value.location,
        'printer_address': value.printer_address,
        'is_enabled': value.is_enabled,
    };
}

