/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSignUpRequest
 */
export interface UserSignUpRequest {
    /**
     * 
     * @type {string}
     * @memberof UserSignUpRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserSignUpRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserSignUpRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UserSignUpRequest interface.
 */
export function instanceOfUserSignUpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function UserSignUpRequestFromJSON(json: any): UserSignUpRequest {
    return UserSignUpRequestFromJSONTyped(json, false);
}

export function UserSignUpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSignUpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'name': json['name'],
    };
}

export function UserSignUpRequestToJSON(value?: UserSignUpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'name': value.name,
    };
}

